### ISSUE TITLE
UI design exploration

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#169]
Q2FY21 total time: 13.5 hrs
- [x] [December 21 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-739988339)
- [x] [November 20 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-724089001)
- [x] [November 6 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-716630641)
- [x] Review meeting with Kathy and Patrick on week of October 4.

Q1FY21 total time: 73 hrs
- [x] [September 28 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-691220953)
- [x] [September 10 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-683853594)
- [x] [August 31 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-674963339)
- [x] [August 18 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-668624379)
- [x] [July 20 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-654280857)
- [x] [July 6 sprint review](https://github.com/seas-computing/course-planner/issues/169#issuecomment-638418839)

###  [gh-pages prototype](https://seas-computing.github.io/course-planner_ux/courses.html) following Mark-One styles *
- [x] All tabs
   - [x] [Accessibility of table headers as they relate to the columns](https://github.com/seas-computing/course-planner/issues/195#issuecomment-620191261)
   - [x] [Accessibility of forms in table headers, with long description and not detected by screen readers as table headers](https://github.com/seas-computing/course-planner/issues/224#issuecomment-635308524)
   - [x] Selection of term drop down above tables
   - [x] Replaced "Settings" with "Options"
- [x] Courses tab and modals ([recommendations](https://github.com/seas-computing/course-planner/issues/169#issuecomment-617349680))
- [x] Non class meetings and modals ([recommendations](https://github.com/seas-computing/course-planner/issues/169#issuecomment-617338954))
   - [x] Populate table with extra rooms per course and the Spring term column
- [x] Faculty tab and modals
- [ ] Schedule tab
- [x] 4 year plan tab
- [x] [Manage courses tab](https://github.com/seas-computing/course-planner/issues/169#issuecomment-625417407)
- [x] [Manage faculty tab](https://seas-computing.github.io/course-planner_ux/manage_faculty.html)

- [x] Style of "Settings" and "Create new..." elements as distinct from the tabs interface

`*`: For the most part, I strictly used the Mark One styles merged on master. Occasionally, Bootstrap code was used for unavailable functionality (i.e.: modal) and relevant user interface elements (i.e.: bordered `div`, stripe-less table, etc.)
